In [1]:
#代码示例：7-1
import pandas as pd
data = pd.read_csv('data_we/Comment.csv')
data.head()

   label                                             review
0      1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1      1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2      1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3      1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4      1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风

In [2]:
#代码示例：7-2
import jieba
train_data = []
for line in data.review:
    line_fenci = jieba.lcut(line)
    train_data.append(line_fenci)

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 1.007 seconds.
Prefix dict has been built succesfully.

In [3]:
#代码示例：7-3
print(train_data[0])
print(train_data[1])
print(train_data[2])

['距离', '川沙', '公路', '较近', ',', '但是', '公交', '指示', '不', '对', ',', '如果', '是', '"', '蔡陆线', '"', '的话', ',', '会', '非常', '麻烦', '.', '建议', '用', '别的', '路线', '.', '房间', '较为简单', '.']
['商务', '大床', '房', '，', '房间', '很大', '，', '床有', '2M', '宽', '，', '整体', '感觉', '经济', '实惠', '不错', '!']
['早餐', '太', '差', '，', '无论', '去', '多少', '人', '，', '那边', '也', '不加', '食品', '的', '。', '酒店', '应该', '重视', '一下', '这个', '问题', '了', '。', '房间', '本身', '很', '好', '。']

In [ ]:
#代码示例：7-4
from gensim.models import Word2Vec
# [旧写法] model = Word2Vec(train_data, size=100, min_count=1)
# ↑ 参数 size 在 gensim 4.0+ 中已重命名为 vector_size
# [新写法] 适用于 gensim >= 4.0
model = Word2Vec(train_data, vector_size=100, min_count=1)

In [6]:
#代码示例：7-5
print(len(model.wv['酒店']))
model.wv['酒店']

100

array([ 1.2913097 ,  1.3787785 ,  1.7766075 ,  0.13462837,  0.21497677,
        0.49974832,  0.10014457, -0.15855487, -0.91300476,  0.22248882,
       -0.12423342, -0.01663428,  0.7000096 ,  0.8872747 ,  0.31214198,
       -0.8608309 ,  1.3592396 , -0.71766096,  0.18247749, -0.5685879 ,
       -1.0136191 ,  1.0021577 , -1.1804698 ,  0.17697957,  0.71453047,
       -0.8107923 ,  0.630949  , -0.3682033 ,  1.3729137 , -1.5849909 ,
       -0.16846952, -1.9750712 ,  1.1182437 ,  0.14051278,  0.49388427,
        1.4990276 , -0.45398152, -0.6103632 ,  0.34369168,  0.18900548,
       -0.9646737 ,  1.2193235 , -0.24389428, -0.7055887 , -1.5632688 ,
       -0.49585143, -1.0720309 ,  0.47048208, -0.08513916, -0.5781224 ,
        0.0510736 ,  1.5568649 , -0.9193901 , -0.24290895,  1.2983334 ,
        0.99009097, -0.5640688 ,  0.46643776, -0.98990035,  0.5253238 ,
        1.2457733 , -1.2432195 , -0.80626005, -1.0739523 , -0.35536364,
        2.057863  , -1.7632767 ,  0.0632392 , -0.55961806, -0.7023979 ,
       -0.20710644,  0.19647117, -0.7298161 ,  0.15582463,  0.26865628,
        0.8857841 ,  1.1338451 , -0.10153551,  1.0020987 , -0.31160632,
       -0.24032862, -0.21235597, -0.18485999, -0.1239932 , -0.44849768,
        0.07965206, -0.01632071,  0.23130189,  0.8771238 , -0.25828993,
        1.9532852 , -0.8803855 ,  0.7336944 ,  0.7767589 , -0.26699522,
       -0.38469738,  0.3227734 , -0.4246916 ,  0.4065846 , -0.25238293],
      dtype=float32)

In [ ]:
#代码示例：7-6
print(model.wv.similarity('酒店', '饭店'))
print(model.wv.similarity('酒店', '不错'))
# [旧写法] for key in model.wv.similar_by_word('不错', topn =5):
# ↑ similar_by_word 在 gensim 4.0+ 中已废弃
# [新写法] 适用于 gensim >= 4.0
for key in model.wv.most_similar('不错', topn =5):
    print(key)

In [11]:
#代码示例：7-7
# 使用pandas读入数据
import pandas as pd
poems_text = pd.read_table('./poems_clean.txt', header=None)
poems_text.columns = ["text"]
# 查看文本
poems_text.head()

                                                text
0  首春:寒随穷律变 春逐鸟声开 初风飘带柳 晚雪间花梅 碧林青旧竹 绿沼翠新苔 芝田初雁去 绮...
1  初晴落景:晚霞聊自怡 初晴弥可喜 日晃百花色 风动千林翠 池鱼跃不同 园鸟声还异 寄言博通者...
2  度秋:夏律昨留灰 秋箭今移晷 峨嵋岫初出 洞庭波渐起 桂白发幽岩 菊黄开灞涘 运流方可叹 含...
3  仪鸾殿早秋:寒惊蓟门叶 秋发小山枝 松阴背日转 竹影避风移 提壶菊花岸 高兴芙蓉池 欲知凉气...
4  山阁晚秋:山亭秋色满 岩牖凉风度 疏兰尚染烟 残菊犹承露 古石衣新苔 新巢封古树 历览情无极...

In [12]:
#代码示例：7-8
import string
import numpy as np
poems_new = []
for line in poems_text['text']:  # poems_text[0]的第0列，指
    title, poem = line.split(':')
    poem = poem.replace(' ', '') #将空格去掉
    poem = 'bbb' + poem
    poems_new.append(list(poem))

In [13]:
#代码示例：7-9
XY  =[]
for poem in poems_new:
    for i in range(len(poem) - 3):
        x1 = poem[i]
        x2 = poem[i+1]
        x3 = poem[i+2]
        
        y = poem[i+3]
        XY.append([x1, x2, x3, y])

In [14]:
# 展示整理后的X和Y的形式
print("原始诗句：")
print(poems_text['text'][3864])
print("\n")
print("训练数据：")
print(["X1", "X2", "X3", "Y"])
for i in range(132763, 132773):
    print(XY[i])

原始诗句：
静夜思:床前明月光 疑是地上霜 举头望明月 低头思故乡


训练数据：
['X1', 'X2', 'X3', 'Y']
['b', 'b', 'b', '床']
['b', 'b', '床', '前']
['b', '床', '前', '明']
['床', '前', '明', '月']
['前', '明', '月', '光']
['明', '月', '光', '疑']
['月', '光', '疑', '是']
['光', '疑', '是', '地']
['疑', '是', '地', '上']
['是', '地', '上', '霜']

In [ ]:
#代码示例7-10
# [旧写法] from keras.preprocessing.text import Tokenizer
# ↑ 独立 keras 包在 TF 2.0+ 中已不推荐使用
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(poems_new)
print(tokenizer.word_index)

#tokenizer默认把0这个索引留个停止词了，其它的词是从1开始索引的。
#然后分类的损失又默认0是第一类
#所以导致假设我们有三个字：a，b，c。
#他们的索引分别是1，2，3，没有0。
#这对keras要使用一个4分类才行
vocab_size = len(tokenizer.word_index) + 1

In [16]:
#代码示例：7-11
XY_digit = np.array(tokenizer.texts_to_sequences(XY))
X_digit = XY_digit[:, :3]
Y_digit = XY_digit[:, 3]
for i in range(132763, 132773):
    print("{:<35}".format(str(XY[i])), "\t", "{:<30}".format(str(list(X_digit[i]))),"\t", Y_digit[i])

['b', 'b', 'b', '床']                	 [1, 1, 1]                      	 533
['b', 'b', '床', '前']                	 [1, 1, 533]                    	 73
['b', '床', '前', '明']                	 [1, 533, 73]                   	 54
['床', '前', '明', '月']                	 [533, 73, 54]                  	 14
['前', '明', '月', '光']                	 [73, 54, 14]                   	 141
['明', '月', '光', '疑']                	 [54, 14, 141]                  	 430
['月', '光', '疑', '是']                	 [14, 141, 430]                 	 45
['光', '疑', '是', '地']                	 [141, 430, 45]                 	 114
['疑', '是', '地', '上']                	 [430, 45, 114]                 	 16
['是', '地', '上', '霜']                	 [45, 114, 16]                  	 203

In [ ]:
#代码示例：7-12
# Embedding + 线性模型
# [旧写法] from keras.layers import Input, Embedding
# [旧写法] from keras.models import Sequential, load_model, Model
# [旧写法] from keras.layers import Input, Dense, Activation, Embedding, Flatten
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.layers import Input, Embedding
from tensorflow.keras.models import Sequential, load_model, Model
from tensorflow.keras.layers import Dense, Activation, Flatten
hidden_size = 256

inp = Input(shape=(3,))
x = Embedding(vocab_size, hidden_size)(inp)
x = Flatten()(x)
x = Dense(vocab_size)(x)
pred = Activation('softmax')(x)

model = Model(inp, pred)
model.summary()

In [ ]:
#代码示例：7-13
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_digit,Y_digit,test_size=0.2, random_state=0)

# [旧写法] from keras.optimizers import Adam
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.optimizers import Adam
# [旧写法] model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(lr=0.001))
# [新写法] 适用于 TensorFlow >= 2.11
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate=0.001))
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), batch_size=10000, epochs=10)

In [17]:
#代码示例：7-14
sample_text = ['床', '前', '明'] 
print(sample_text)
sample_index = tokenizer.texts_to_sequences(sample_text)
print(sample_index)
word_prob = model.predict(np.array(sample_index).reshape(1, 3))[0]
print(tokenizer.index_word[word_prob.argmax()], word_prob.max())

['床', '前', '明']
[[533], [73], [54]]
月 0.29370514

In [18]:
#代码示例：7-15
poem_incomplete = 'bbb熊****大****很****帅****'
poem_index = []
poem_text = ''
for i in range(len(poem_incomplete)):
    current_word = poem_incomplete[i]
    
    if  current_word != '*':
        # 给定的词
        index = tokenizer.word_index[current_word]
    else:
        # 根据前三个词预测 *
        x = poem_index[-3:]
        y = model.predict(np.expand_dims(x, axis=0))[0]
        index = y.argmax()
        current_word = tokenizer.index_word[index]


    poem_index.append(index)
    poem_text = poem_text + current_word
        

poem_text = poem_text[3:]
print(poem_text[0:5])
print(poem_text[5:10])
print(poem_text[10:15])
print(poem_text[15:20])

熊马蹄迟迟
大夫子不知
很氏者何处
帅相思不可

In [1]:
#代码示例7-16
import string
import numpy as np

f = open('poems_clean.txt', "r", encoding='utf-8')
poems = []
for line in f.readlines():
    title, poem = line.split(':')
    poem = poem.replace(' ', '') #将空格去掉
    poem = poem.replace('\n', '') #将换行符去掉
    poems.append(list(poem))    
print(poems[0][:])

['寒', '随', '穷', '律', '变', '春', '逐', '鸟', '声', '开', '初', '风', '飘', '带', '柳', '晚', '雪', '间', '花', '梅', '碧', '林', '青', '旧', '竹', '绿', '沼', '翠', '新', '苔', '芝', '田', '初', '雁', '去', '绮', '树', '巧', '莺', '来']

In [ ]:
#代码示例：7-17
# [旧写法] from keras.preprocessing.text import Tokenizer
# [旧写法] from keras.preprocessing.sequence import pad_sequences
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer()
tokenizer.fit_on_texts(poems)
poems_digit = tokenizer.texts_to_sequences(poems)
vocab_size = len(tokenizer.word_index) + 1 #加上停止词0
vocab_size #有多少个不同的字

In [ ]:
#代码示例：7-18
#为了将所有的诗放在一个M*N的np.array中，将每一首诗补0到同样的长度
# [旧写法] from keras.preprocessing.sequence import pad_sequences（已在上方导入）
poems_digit = pad_sequences(poems_digit, maxlen=50, padding='post')
print("原始诗歌")
print(poems[3864])
print("\n")
print("编码+补全后的结果")
print(poems_digit[3864])

In [4]:
#代码示例：7-19
X = poems_digit[:, :-1]
Y = poems_digit[:, 1:]

print(poems_digit.shape)
print(X.shape)
print(Y.shape)

print("X示例", "\t", "Y示例")

for i in range(10):
    print(X[0][i], "\t", Y[0][i])
    
print("...", "\t", "...")

(24117, 50)
(24117, 49)
(24117, 49)
X示例 	 Y示例
42 	 180
180 	 401
401 	 1143
1143 	 671
671 	 9
9 	 331
331 	 130
130 	 58
58 	 84
84 	 177
... 	 ...

In [ ]:
#代码示例：7-20
#内存不足报错已解决，修改keras包目录下np_utils.py文件中的to_categorical函数dtype参数默认为'int8'即可
print(vocab_size)
# [旧写法] from keras.utils import to_categorical
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.utils import to_categorical
Y = to_categorical(Y, num_classes=vocab_size)
print(Y.shape)

In [ ]:
#代码示例：7-21
# [旧写法] from keras.models import Model
# [旧写法] from keras.layers import Input, SimpleRNN, Dense, Embedding, Activation, BatchNormalization
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, SimpleRNN, Dense, Embedding, Activation, BatchNormalization
embedding_size = 64
hidden_size = 128

In [8]:
#代码示例：7-22
inp = Input(shape=(49,))
# Encoder
x = Embedding(vocab_size, embedding_size, mask_zero=True)(inp)
x = SimpleRNN(hidden_size,return_sequences=True)(x)
# prediction
x = Dense(vocab_size)(x)
pred = Activation('softmax')(x)

model = Model(inp, pred)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
input_1 (InputLayer)         (None, 49)                0
_________________________________________________________________
embedding_1 (Embedding)      (None, 49, 64)            354944
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 49, 128)           24704
_________________________________________________________________
dense_1 (Dense)              (None, 49, 5546)          715434
_________________________________________________________________
activation_1 (Activation)    (None, 49, 5546)          0
=================================================================
Total params: 1,095,082
Trainable params: 1,095,082
Non-trainable params: 0
_________________________________________________________________

In [ ]:
#代码示例：7-23
# [旧写法] from keras.optimizers import Adam
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.optimizers import Adam
# [旧写法] model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=0.001), metrics=['accuracy'])
# [新写法] 适用于 TensorFlow >= 2.11
model.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])
model.fit(X, Y, epochs=10, batch_size=128, validation_split=0.2)

In [11]:
#代码示例：7-24
poem_incomplete = '熊****大****很****帅****'
poem_index = []
poem_text = ''
for i in range(len(poem_incomplete)):
    current_word = poem_incomplete[i]
    
    if  current_word != '*':
        index = tokenizer.word_index[current_word]
        
    else:
        x = np.expand_dims(poem_index, axis=0)
        x = pad_sequences(x, maxlen=49, padding='post')
        y = model.predict(x)[0, i]
        
        y[0] = 0            #去掉停止词
        index = y.argmax()
        current_word = tokenizer.index_word[index]
        
    poem_index.append(index)
    poem_text = poem_text + current_word
        
poem_text = poem_text[0:]
print(poem_text[0:5])
print(poem_text[5:10])
print(poem_text[10:15])
print(poem_text[15:20])

熊颀里无人
大青门不知
很不知何处
帅何处不知

In [12]:
#代码示例：7-25
import string
import numpy as np

f = open('./poems_clean.txt', "r", encoding='utf-8')
poems = []
for line in f.readlines():
    title, poem = line.split(':')
    poem = poem.replace(' ', '') #将空格去掉
    poem = poem.replace('\n', '') #将换行符去掉
    poems.append(list(poem))
    
print(poems[0][:])

['寒', '随', '穷', '律', '变', '春', '逐', '鸟', '声', '开', '初', '风', '飘', '带', '柳', '晚', '雪', '间', '花', '梅', '碧', '林', '青', '旧', '竹', '绿', '沼', '翠', '新', '苔', '芝', '田', '初', '雁', '去', '绮', '树', '巧', '莺', '来']

In [ ]:
#代码示例：7-26
# [旧写法] from keras.preprocessing.text import Tokenizer
# [旧写法] from keras.preprocessing.sequence import pad_sequences
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer()
tokenizer.fit_on_texts(poems)
vocab_size = len(tokenizer.word_index) + 1 #加上停止词0
poems_digit = tokenizer.texts_to_sequences(poems)
#为了将所有的诗放在一个M*N的np.array中，将每一首诗补0到同样的长度
poems_digit = pad_sequences(poems_digit, maxlen=50, padding='post')

In [14]:
#代码示例：7-27
X = poems_digit[:, :-1]
Y = poems_digit[:, 1:]
print("X示例", "\t", "Y示例")

for i in range(10):
    print(X[0][i], "\t", Y[0][i])
    
print("...", "\t", "...")

X示例 	 Y示例
42 	 180
180 	 401
401 	 1143
1143 	 671
671 	 9
9 	 331
331 	 130
130 	 58
58 	 84
84 	 177
... 	 ...

In [ ]:
#代码示例：7-28
# [旧写法] from keras.utils import to_categorical
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.utils import to_categorical
Y = to_categorical(Y, num_classes=vocab_size)
print(Y.shape)

In [ ]:
#代码示例：7-29
# [旧写法] from keras.layers import Input, LSTM, Dense, Embedding, Activation, BatchNormalization
# [旧写法] from keras import Model
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.layers import Input, LSTM, Dense, Embedding, Activation, BatchNormalization
from tensorflow.keras import Model

hidden_size1 = 128
hidden_size2 = 64

inp = Input(shape=(49,))

# Encoder
x = Embedding(vocab_size, hidden_size1, input_length=49, mask_zero=True)(inp)
x = LSTM(hidden_size2, return_sequences=True)(x)

# prediction
x = Dense(vocab_size)(x)
pred = Activation('softmax')(x)

model = Model(inp, pred)
model.summary()

In [ ]:
#代码示例：7-30
# [旧写法] from keras.optimizers import Adam
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.optimizers import Adam
# [旧写法] model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=0.01), metrics=['accuracy'])
# [新写法] 适用于 TensorFlow >= 2.11
model.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=0.01), metrics=['accuracy'])
model.fit(X, Y, epochs=10, batch_size=128, validation_split=0.2)

In [18]:
#代码示例：7-31
poem_incomplete = '熊****大****很****帅****'
poem_index = []
poem_text = ''
for i in range(len(poem_incomplete)):
    current_word = poem_incomplete[i]
    
    if  current_word != '*':
        index = tokenizer.word_index[current_word]
        
    else:
        x = np.expand_dims(poem_index, axis=0)
        x = pad_sequences(x, maxlen=49, padding='post')
        y = model.predict(x)[0, i]
        
        y[0] = 0            #去掉停止词
        index = y.argmax()
        current_word = tokenizer.index_word[index]
        

    poem_index.append(index)
    poem_text = poem_text + current_word
        
poem_text = poem_text[0:]
print(poem_text[0:5])
print(poem_text[5:10])
print(poem_text[10:15])
print(poem_text[15:20])

熊踞枝红粉
大金罍带翠
很金谷不知
帅明月满庭

In [1]:
#代码示例：7-32
import string
import jieba

English = []
Chinese = []

f = open('./cmn.txt', "r", encoding='utf-8')
for line in f.readlines():
    # In each line, the data is of format:
    #    He ran.	他跑了。
    eng, chs = line.strip().split('\t')
    
    eng = eng[:-1]
    eng = eng.split(' ')
    English.append(eng)
    
    #分词
    chs = jieba.lcut(chs)
    chs = ['B'] + chs
    Chinese.append(chs)

# Example Print
print(English[20000])
print(Chinese[20000])

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.488 seconds.
Prefix dict has been built succesfully.

['If', 'I', 'were', 'you,', "I'd", 'want', 'to', 'know', 'what', 'Tom', 'is', 'doing', 'right', 'now']
['B', '如果', '我', '是', '你', '，', '我', '不会', '想', '去', '知道', 'Tom', '现在', '正在', '做', '什么', '。']

In [ ]:
#代码示例：7-33
# [旧写法] from keras.preprocessing.text import Tokenizer
# [旧写法] from keras.preprocessing.sequence import pad_sequences
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Process English Data
tokenizer_eng = Tokenizer()
tokenizer_eng.fit_on_texts(English)
eng_vocab_size = len(tokenizer_eng.word_index) + 1

# Process Chinese Data
tokenizer_chs = Tokenizer()
tokenizer_chs.fit_on_texts(Chinese)
chs_vocab_size = len(tokenizer_chs.word_index) + 1

print("英文字典的大小,",eng_vocab_size)
print("中文字典的大小,",chs_vocab_size)

In [3]:
#代码示例：7-34
#补全英文样本
max_length=40
eng_digit = tokenizer_eng.texts_to_sequences(English)
eng_digit = pad_sequences(eng_digit, maxlen=max_length, padding='post')

#补全中文样本
chs_digit = tokenizer_chs.texts_to_sequences(Chinese)
chs_digit = pad_sequences(chs_digit, maxlen=max_length, padding='post')

print("展示补全后的数据维度")
print(eng_digit.shape)
print(chs_digit.shape)
print("\n")

print("展示第6条样本")
print(English[6])
print(Chinese[6])
print("\n")

print("展示处理后的结果")
print(eng_digit[6])
print(chs_digit[6])

展示补全后的数据维度
(20403, 40)
(20403, 40)


展示第6条样本
['I', 'won']
['B', '我', '赢', '了', '。']


展示处理后的结果
[  2 757   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0]
[  1   3 873   5   2   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0]

In [4]:
#代码示例：7-35
X_eng = eng_digit
X_chs = chs_digit[:, :-1]
Y = chs_digit[:, 1:]
print(X_eng.shape)
print(X_chs.shape)
print(Y.shape)

(20403, 40)
(20403, 39)
(20403, 39)

In [ ]:
#代码示例：7-36
# [旧写法] from keras.utils import to_categorical
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.utils import to_categorical
Y = to_categorical(Y, num_classes=chs_vocab_size)
print(Y.shape)

In [ ]:
#代码示例：7-37
# [旧写法] from keras.layers import Input, LSTM, Dense, Embedding
# [旧写法] from keras.models import Model, load_model
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.layers import Input, LSTM, Dense, Embedding
from tensorflow.keras.models import Model, load_model
hidden_size_1 = 64
hidden_size_2 = 128

encoder_input = Input(shape = (max_length,))
x = Embedding(eng_vocab_size, hidden_size_1, mask_zero=True, name='ENG')(encoder_input)
encoder_output,encoder_h,encoder_c = LSTM(hidden_size_2, return_state=True, name='Encoder')(x)

encoder_state = [encoder_h,encoder_c]

In [7]:
#代码示例：7-38
decoder_input = Input(shape=(max_length-1, ))
x = Embedding(chs_vocab_size, hidden_size_1, mask_zero=True, name='CHS')(decoder_input)
decoder_output = LSTM(hidden_size_2, return_sequences=True, name='Decoder')(x, initial_state=encoder_state)

pred = Dense(chs_vocab_size, activation='softmax')(decoder_output)

In [8]:
#代码示例：7-39
model = Model([encoder_input,decoder_input],pred)
model.summary()
chs_vocab_size

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_1 (InputLayer)            (None, 40)           0
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 39)           0
__________________________________________________________________________________________________
ENG (Embedding)                 (None, 40, 64)       456704      input_1[0][0]
__________________________________________________________________________________________________
CHS (Embedding)                 (None, 39, 64)       875584      input_2[0][0]
__________________________________________________________________________________________________
Encoder (LSTM)                  [(None, 128), (None, 98816       ENG[0][0]
__________________________________________________________________________________________________
Decoder (LSTM)                  (None, 39, 128)      98816       CHS[0][0]
                                                                 Encoder[0][1]
                                                                 Encoder[0][2]
__________________________________________________________________________________________________
dense_1 (Dense)                 (None, 39, 13681)    1764849     Decoder[0][0]
==================================================================================================
Total params: 3,294,769
Trainable params: 3,294,769
Non-trainable params: 0
__________________________________________________________________________________________________

13681

In [ ]:
#代码示例：7-40
# [旧写法] from keras.optimizers import Adam
# [新写法] 适用于 TensorFlow >= 2.0
from tensorflow.keras.optimizers import Adam
# [旧写法] model.compile(loss='categorical_crossentropy', optimizer=Adam(lr=0.01), metrics=['accuracy'])
# [新写法] 适用于 TensorFlow >= 2.11
model.compile(loss='categorical_crossentropy', optimizer=Adam(learning_rate=0.01), metrics=['accuracy'])
model.fit([X_eng, X_chs], Y, epochs=10, batch_size=512, validation_split=0.2)

In [ ]:
#代码示例：7-41
import numpy as np

test = 'what is your favorite drink'
test = [test.split(' ')]
test = tokenizer_eng.texts_to_sequences(test)
test = pad_sequences(test, maxlen=max_length, padding='post')
# [旧写法] predict = np.ones((1, max_length -1), dtype=np.int) * tokenizer_chs.word_index['b']
# ↑ np.int 在 NumPy 1.20 中已废弃，1.24 中已移除
# [新写法] 适用于 NumPy >= 1.20
predict = np.ones((1, max_length -1), dtype=np.int64) * tokenizer_chs.word_index['b']

chinese = ''

for i in range(max_length):
    output = model.predict([test, predict])
    predict[0, i + 1] = np.argmax(output[0, i])
    
    if predict[0, i + 1] == 0:
        break
        
    chinese = chinese + tokenizer_chs.index_word[predict[0, i + 1]]

print(chinese)